[package]
name = "media-organizer"
version = "0.1.0"
authors = ["Baptiste Lombardo <blombardo@ownpage.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
