version: '3'
services:
  # Tool / services
  media-organizer:
    build:
      context: .
    volumes:
      - ../media-organizer-tests:/files
    environment:
      - INPUT_DIR=/files/downloads
      - LIBRARY_DIR=/files/library
